# Generated by Django 4.2.13 on 2024-12-17 21:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investigation_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='lmodel',
        ),
        migrations.CreateModel(
            name='InvestigationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Результат словами')),
                ('value', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Вероятность')),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='core.investigation', verbose_name='Исследование')),
                ('lmodel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_values', to='core.learnigmodel', verbose_name='Обучаемая модель')),
            ],
            options={
                'verbose_name': 'Значение исследования',
                'verbose_name_plural': 'Значения исследований',
            },
        ),
    ]
