# Generated by Django 4.2.13 on 2024-12-17 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_investigation_lmodel_investigationvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='value',
        ),
        migrations.AddField(
            model_name='investigation',
            name='value_mean',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Средняя вероятность'),
        ),
    ]
